=== jumpinjackie/mapguide-maestro/MaestroAPI/Schemas/SiteInformation-1.0.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
  <xs:element name="SiteInformation">
    <xs:annotation>
      <xs:documentation>Site Information</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element name="SiteServer">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="DisplayName" type="xs:string"/>
              <xs:element name="Status" type="xs:string"/>
              <xs:element name="Version" type="xs:string"/>
              <xs:element name="OperatingSystem">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="AvailablePhysicalMemory" type="xs:integer"/>
                    <xs:element name="TotalPhysicalMemory" type="xs:integer"/>
                    <xs:element name="AvailableVirtualMemory" type="xs:integer"/>
                    <xs:element name="TotalVirtualMemory" type="xs:integer"/>
                    <xs:element name="Version" type="xs:string"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Statistics">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="AdminOperationsQueueCount" type="xs:integer"/>
              <xs:element name="ClientOperationsQueueCount" type="xs:integer"/>
              <xs:element name="SiteOperationsQueueCount" type="xs:integer"/>
              <xs:element name="AverageOperationTime" type="xs:integer"/>
              <xs:element name="CpuUtilization" type="xs:integer"/>
              <xs:element name="TotalOperationTime" type="xs:integer"/>
              <xs:element name="ActiveConnections" type="xs:integer"/>
              <xs:element name="TotalConnections" type="xs:integer"/>
              <xs:element name="TotalOperationsProcessed" type="xs:integer"/>
              <xs:element name="TotalOperationsReceived" type="xs:integer"/>
              <xs:element name="Uptime" type="xs:integer"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== jumpinjackie/mapguide-maestro/OSGeo.MapGuide.MaestroAPI.Tests/Resources/GetSiteInfo.xml
<?xml version="1.0" encoding="UTF-8"?>
<SiteInformation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="SiteInformation-1.0.0.xsd">
	<SiteServer>
		<DisplayName></DisplayName>
		<Status>Online</Status>
		<Version>4.0.0.9862</Version>
		<OperatingSystem>
			<AvailablePhysicalMemory>13408378880</AvailablePhysicalMemory>
			<TotalPhysicalMemory>34281869312</TotalPhysicalMemory>
			<AvailableVirtualMemory>140732317147136</AvailableVirtualMemory>
			<TotalVirtualMemory>140737488224256</TotalVirtualMemory>
			<Version>Microsoft WindowsHome Edition  (Build 9200)</Version>
		</OperatingSystem>
	</SiteServer>
	<Statistics>
		<AdminOperationsQueueCount>0</AdminOperationsQueueCount>
		<ClientOperationsQueueCount>0</ClientOperationsQueueCount>
		<SiteOperationsQueueCount>0</SiteOperationsQueueCount>
		<AverageOperationTime>47</AverageOperationTime>
		<CpuUtilization>0</CpuUtilization>
		<TotalOperationTime>2</TotalOperationTime>
		<ActiveConnections>2</ActiveConnections>
		<TotalConnections>11</TotalConnections>
		<TotalOperationsProcessed>42</TotalOperationsProcessed>
		<TotalOperationsReceived>43</TotalOperationsReceived>
		<Uptime>2588</Uptime>
	</Statistics>
</SiteInformation>
